### PR TITLE
add crossroad detector 093

### PR DESCRIPTION
**Pull request by ygnn123**
**Before submitting a pull request**, please make sure the following is done:

1. You have merged in the latest changes from `develop`.
2. Resolved any conflicts that may have happened from that merge.
3. Ensure that you have run all tests and linting locally.

### CODE REVIEW

**Comment by snosov1** [comment]
@AlexanderDokuchaev Alexander, please, take a look

**Comment by snosov1** [comment]
@ygnn123 CI is red, please, fix

**Comment by ygnn123** [comment]
@snosov1 Done

**Comment by snosov1** [comment]
@AlexanderDokuchaev Alexander, can you, please, review?

**Pull request merged**
