### PR TITLE
Merge NNCF to OTE

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson maybe it is time to remove `nncf` folder from `training_extensions` ?

**Comment by LeonidBeynenson** [comment]
> @LeonidBeynenson maybe it is time to remove `nncf` folder from `training_extensions` ?

YESS!

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson please do it.

**Comment by AlexKoff88** [comment]
Can we define ETA for this PR? It's been a long time since it was opened. 

@LeonidBeynenson, do you need any help from our side?

**Comment by Ilya-Krylov** [comment]
@AlexKoff88 it will be merged as soon as corresponding openvinotoolkit/mmdetection PR is merged

**Comment by AlexKoff88** [comment]
> @AlexKoff88 it will be merged as soon as corresponding openvinotoolkit/mmdetection PR is merged

Ok. Any ETA for that MR?

**Comment by Ilya-Krylov** [comment]
@AlexKoff88 I think probably this week, but @druzhkov-paul might have another opinion

**Comment by druzhkov-paul** [comment]
I won't be that optimistic saying that it'll happen this week. I'd say, the end of the next week sounds reasonable. It might happen earlier though.

**Comment by druzhkov-paul** [comment]
And BTW AFAIK discussing this PRs we're only talking about initial support of NNCF in OTE/detection part. A lot of stuff is still TBD on the models' coverage side. @LeonidBeynenson @aleksei-kashapov please correct me, if I'm wrong.

**Comment by AlexKoff88** [comment]
@druzhkov-paul, you are right. The plan is to have NNCF integrated into other templates. But we need to have the initial version that covers basic 1-stage detectors from mmdetection as soon as possible.

**Comment by Ilya-Krylov** [comment]
@AlexKoff88 @LeonidBeynenson @aleksei-kashapov 

Even we agree to merge PRs as they are, there is no implementation that would bind template.yaml with actual training/quantization code, there is no nncf API examples exposed to template.yaml.

**Comment by AlexKoff88** [comment]
@Ilya-Krylov, the only API we agreed to expose for now is a turning on/off optimization algorithms, e.g. quantization: True.

**Comment by Ilya-Krylov** [comment]
@AlexKoff88 it is up to you, but there are no working examples yet.

**Comment by LeonidBeynenson** [comment]
2 @Ilya-Krylov , @AlexKoff88 :    
I'm going to start implementing that in OTE as soon as I finish my current work.    
Hope to have it during next 2 weeks.

But I need to have this PR and PR in mmdetection merged for that...

**Comment by LeonidBeynenson** [comment]
Please, note that as soon as we merge my main mmdetection PR    
https://github.com/openvinotoolkit/mmdetection/pull/73     
I will update this PR and the new mmdetection will be ready to be used from ote.

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson It is no stopper for you if these PR are not merged. Merging this PR does not bring new stuff to OTE, it simply removes NNCF from its tree.

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson This branch has conflicts that must be resolved

**Comment by LeonidBeynenson** [comment]
http://134.191.240.124/job/ote/job/precommit/job/trigger/965/console -- SUCCESS

**Comment by LeonidBeynenson** [comment]
2 @Ilya-Krylov :  Ilya, is this PR ready for merge now?  
If yes, please, merge it!  
If now, please, say me what should be fixed!

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
