### PR TITLE
Update NNCF configs

### PR DESCRIPTION
**Pull request by kshpv**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson @aleksei-kashapov if it is not going to be merged please close, otherwise do something

**Comment by LeonidBeynenson** [comment]
2 @Ilya-Krylov : Ilya, I think that these changes should be merged to develop
But I would like to re-check that and ask Aleksei about this PR.
It may require couple of days, since Aleksei is in vacation right now.

**Comment by Ilya-Krylov** [comment]
@aleksei-kashapov @LeonidBeynenson will you make it up to date or close?

**Comment by aleksei-kashapov** [comment]
@Ilya-Krylov ,please, merge

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
