### PR TITLE
[Segmentation] Updates OTESeg

### PR DESCRIPTION
**Pull request by evgeny-izutov**
Updates OTESeg:
* Enables Adaptive Dataset Repetition
* Adds collecting meta info for active learning
* Fixes learning curves
* Adds label schema storing in a model
* Updates POT config
* Adds base task capabilities to model templates

Build on BMM: 20046 ✔️ 
Train on BMM: ✔️

### CODE REVIEW

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
