### PR TITLE
Add support of alt_ssd_export for NNCF models

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
Should be merge with https://github.com/openvinotoolkit/mmdetection/pull/135

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson please have a look

**Comment by LeonidBeynenson** [comment]
run tests

**Comment by LeonidBeynenson** [comment]
2 @AlexanderDokuchaev : Alexander, have you checked on your desktop that after these changes the export in tests is done for NNCF models both with and without `--alt-ssd-export` option?
And everything works smoothly for all NNCF models?

**Comment by AlexanderDokuchaev** [comment]
@LeonidBeynenson i have checked several model with difference option (nncf / no nncf / alt_ssd / no alt_ssd) and it looks ok

**Review by LeonidBeynenson — APPROVED** [review]

**Comment by AlexanderDokuchaev** [comment]
@Ilya-Krylov Linter fixed. 
Other problem is ` AssertionError: Export of NNCF-compressed model is incompatible with --alt_ssd_export`, it's expected, need update mmdetection with https://github.com/openvinotoolkit/mmdetection/pull/135.

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev This branch has conflicts that must be resolved

**Comment by Ilya-Krylov** [comment]
run tests

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
